name: Scheduled Python Script

on:
  schedule:
    - cron: '0 12 * * *'   # 每天 UTC 12:00 = 台灣時間 20:00
  workflow_dispatch:        # 允許手動執行

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      TO_EMAILS: ${{ secrets.TO_EMAILS }}
      FINMIND_API_TOKEN: ${{ secrets.FINMIND_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check secrets
        run: |
          if [ -z "$SENDGRID_API_KEY" ]; then
            echo "SENDGRID_API_KEY is empty"
            exit 1
          fi
          if [ -z "$FINMIND_API_TOKEN" ]; then
            echo "FINMIND_API_TOKEN is empty"
            exit 1
          fi

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python Script
        run: python main.py